apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init
spec:
  template:
    spec:
      containers:
        - name: mongo-init
          image: mongo:4.0.8
          command:
            - mongo
            - "mongo-0.mongo.default.svc.cluster.local:27017"
            - "-u"
            - "root"
            - "-p"
            - "password"
            - "--authenticationDatabase"
            - "admin"
            - "--eval"
            - |
              rs.initiate({
                _id: "rs0",
                members: [
                  { _id: 0, host: "mongo-0.mongo.default.svc.cluster.local:27017" },
                  { _id: 1, host: "mongo-1.mongo.default.svc.cluster.local:27017" },
                  { _id: 2, host: "mongo-2.mongo.default.svc.cluster.local:27017" }
                ]
              })
      restartPolicy: OnFailure
