apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2025-05-03T11:07:26Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: sit737-10-1p
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:allocateLoadBalancerNodePorts: {}
        f:externalTrafficPolicy: {}
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":3000,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: unknown
    operation: Update
    time: "2025-05-03T11:07:26Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"service.kubernetes.io/load-balancer-cleanup": {}
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: cloud-controller-manager
    operation: Update
    subresource: status
    time: "2025-05-03T11:08:15Z"
  name: sit737-10-1p-service
  namespace: default
  resourceVersion: "4921"
  uid: 60a1712d-16d0-48d2-963d-2cf73f7a29e6
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.225.156
  clusterIPs:
  - 34.118.225.156
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31629
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: sit737-10-1p
    app.kubernetes.io/managed-by: cloud-console
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.129.165.123
      ipMode: VIP
