apiVersion: v1
kind: Service
metadata:
  name: mongodb-rs
  namespace: default
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: mongo-pod-port
  selector:
    app: mongodb-rs
  type: ClusterIP