apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: account-service
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - image: australia-southeast2-docker.pkg.dev/striped-sunspot-458709-h2/sit737/account-service:v1
        name: account-service
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-auth
              key: mongo-root-username
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongodb-auth
              key: mongo-root-password
        - name: MONGO_HOSTS
          valueFrom:
            configMapKeyRef:
              name: app-cm
              key: MONGO_HOSTS
        - name: MONGO_REPLICA_SET
          valueFrom:
            configMapKeyRef:
              name: app-cm
              key: MONGO_REPLICA_SET
        - name: BALANCE_SERVICE
          valueFrom:
            configMapKeyRef:
              name: app-cm
              key: BALANCE_SERVICE
        - name: ACCOUNT_SERVICE
          valueFrom:
            configMapKeyRef:
              name: app-cm
              key: ACCOUNT_SERVICE
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"