apiVersion: v1
kind: Service
metadata:
  labels:
    app: balance-service-svc
  name: balance-service-svc
spec:
  clusterIP: None
  ports:
  - name: 3000-80
    port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    app: balance-service
  type: ClusterIP