apiVersion: v1
kind: Service
metadata:
  labels:
    app: sit737-61p-service
  name: sit737-61p-service
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: sit737-61p-service
  type: NodePort
