apiVersion: v1
kind: Service
metadata:
  labels:
    app: client-interface-svc
  name: client-interface-svc
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: client-interface
  type: NodePort