apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-web
  name: node-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-web
  template:
    metadata:
      labels:
        app: node-web
    spec:
      containers:
      - image: chrisyp/sit737-91p:v1
        name: sit737-91p
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: "mongodb://$(MONGO_USER):$(MONGO_PASS)@mongo-service:27017"
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-username
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"